### ISSUE TITLE
Add Media and Entertainment Interest Group

### ISSUE THREAD

**Issue by chrisn** [w3c/web-networks-charter#12]
As video is an important driver of network usage, I recommend adding [Media and Entertainment Interest Group](https://www.w3.org/2011/webtv/) to the list of W3C Groups in the Coordination section.

**Comment by sudeepdi** [comment]
I agree. I will make the update and send it for review and merge.

**Comment by sudeepdi** [comment]
@dontcallmedom @anssiko @chrisn : I have submitted a PR. Please review and merge.
