### ISSUE TITLE
Note IEEE in External Organizations

### ISSUE THREAD

**Issue by anssiko** [w3c/web-networks-charter#6]
The family of IEEE 802.11 standards that cover Wireless LAN seem relevant to this IG.

As an example of a related concrete work item, this IG could help provide insight and help ensure accuracy of data such as [maximum downlink speeds](http://wicg.github.io/netinfo/#max-downlink-table) in Network Information API.

**Comment by sudeepdi** [comment]
Yes, and there could other parameters of interest to applications (information about backhaul congestion, network switching time, etc).  And some of these inputs can come via organizations like IEEE. I agree with the suggestion that IEEE should be added in External Organizations list.

**Comment by anssiko** [comment]
@sudeepdi thanks for you suggestions. I submitted a PR that attempts to address this issue, please see #8.
