### ISSUE TITLE
Relationship with Web Performance Working Group

### ISSUE THREAD

**Issue by jonathanding** [w3c/web-networks-charter#7]
The Web Networks is expected to have some interoperable areas with specs in Web Performance Working Group. For example, Resource Timing API in Web Performance contains information about network performance, such as time for DNS lookup, time to establish TCP connections, etc. Efforts in Web Networks potentially further expose more underlying details of the characteristics and measurements of the network stack, which would be good complements / enhancements for existing specs of Web Performance to help to profiling and diagnosing the network part of Web app.

I suggest to mention this in section 3.1 (W3C Groups) to reflect this collaboration opportunity.

**Comment by sudeepdi** [comment]
Its a good suggestion. Thank you. We will add Web Performance WG info in Section 3.1 and upload the updated version.

**Comment by sudeepdi** [comment]
@anssiko @dontcallmedom. I submitted a PR that attempts to address this issue. Please see #9 .

**Comment by anssiko** [comment]
@jonathanding, we added Web Performance WG to the charter per your recommendation:

https://w3c.github.io/web-networks-charter/#coordination

Please let us know if you have further suggestions, or comments.

**Comment by jonathanding** [comment]
@anssiko Thanks and LGTM.
